apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 8085          # Service port
      targetPort: http-web-app  # Matches container port name
